import pandas as pd
import json
import os

def generate_food_metadata(excel_path='food_spoliage_final.xlsx', output_path='food_metadata.json'):
    print(f"Loading data from {excel_path}...")
    df = pd.read_excel(excel_path)
    
    metadata = {
        "food_map": {},
        "thresholds": {}
    }
    
    # Extract unique foods and their corresponding categories
    unique_foods = df[['Food_Category', 'Food_Name']].drop_duplicates()
    
    for _, row in unique_foods.iterrows():
        cat = row['Food_Category']
        food = row['Food_Name']
        
        if cat not in metadata["food_map"]:
            metadata["food_map"][cat] = []
            
        if food not in metadata["food_map"][cat]:
            metadata["food_map"][cat].append(food)
            
    # Remove NaN values from food_map if any exist
    for cat in list(metadata["food_map"].keys()):
        if pd.isna(cat):
            del metadata["food_map"][cat]
            continue
        metadata["food_map"][cat] = [f for f in metadata["food_map"][cat] if not pd.isna(f)]
            
    # Calculate median threshold values for each food item to be used as lookup
    agg_funcs = {
        'Min_Optimal_Temp_C': 'median',
        'Max_Optimal_Temp_C': 'median',
        'Min_Optimal_Humidity_Pct': 'median',
        'Max_Optimal_Humidity_Pct': 'median',
        'Base_Shelf_Life_Hours': 'median'
    }
    
    food_thresholds = df.groupby('Food_Name').agg(agg_funcs).to_dict('index')
    
    # Store thresholds
    for food, metrics in food_thresholds.items():
        if not pd.isna(food):
            metadata["thresholds"][food] = metrics
            
    # Calculate category defaults in case a food is missing
    cat_thresholds = df.groupby('Food_Category').agg(agg_funcs).to_dict('index')
    for cat in list(metadata["food_map"].keys()):
        if cat in cat_thresholds:
            # We'll save this in metadata directly, but wait `app.py` tries to load category_defaults from the `metadata.json` generated by trainmodel... wait, no, `app.py` expects it from `metadata.json`:
            # item_thresholds = metadata.get('category_defaults', {}).get(category, {})
            pass
            
    # Actually, let's put category_defaults inside food_metadata just in case, or we can use it here
    metadata["category_defaults"] = cat_thresholds

    with open(output_path, 'w') as f:
        json.dump(metadata, f, indent=4)
        
    print(f"Generated {output_path} successfully.")
    print(f"Categories extracted: {len(metadata['food_map'])}")
    print(f"Food items extracted: {len(metadata['thresholds'])}")

if __name__ == "__main__":
    generate_food_metadata()
